algo = input ('digite algo: ')  
print('O tipo primitvo desse valor e : ', type(algo)) 
print ('Esse tipo tem espaços? ', algo.isspace() )   
print ('E um numero ?', algo.isnumeric())
print('E alfabetico? ', algo.isalpha())
print('E alfanumerico ? ', algo.isalnum())
print('Estar em maiusculas ? ', algo.isupper())
print('Esta em minusculas? ', algo.islower() )
print('Esta capitalizado?', algo.istitle())