'''FATIAMENTO DE STR
FRASE =  'CURSO EM VIDEO PYTHON '
FRASE [9] = V
FRASE [9:13] === VIDE
FRASE [9:21:2 VAI PULAR DOIS ]

'''
'''
ANALISE=================='CURSO' in FRASE === CTRL + F 


ANALISE=========FIND E ENCONTRAR ('DEO') QUANTAS VEZES ELE ENCONTROU DENTRO DA STR ESSE OBJETO  E EM QUAL POSIÇÃO DA STR O OBJETO TAVA, SE O OBJETO NAO FOR ENCONTRA O RETORNO E -1

ANALISE =========   COUNT E CONTAR ('O') QUANTAS VEZES TEM O OBJETO ESPECIFICADO 

ANALISE =========   LEN PARA LER DENTRO DE UM STR, SABER O COMPRIMENTO 

FRASE = 'CURSO EM VIDEO PYTHON'

TRASFORMAÇÃO=================
FRASE.REPLACE('PYTHON','ANDROID') O COMANDO REPLACE E PARA SUBSTITUIR UMA FRAE EM STR

''' '''
TRASFORMAÇÃO============
FRASE.upper maiuscula

TRASFORMAÇÃO===============
FRASE.lower minuscular 

TRANSFORMAÇÃO======== 
FRASE.CAPITALIZE DEIXA E PRIMEIRA LETRA DE TODA A STR EM LETRA MAIUSCULAR SENDO QUE ELE JOGOU TODAS AS OUTRAS LETRA EM MINUSCULAS

TRANSFORMAÇÃO=============
FRASE.TITLE VAI ANALISA QUANTAS PALAVRAS TEM A STR E VAI DEIXA SO A PRIMEIRA LETRA MAIUSCULA FAZENDO UMA QUEBRA DE LINHA


TRANSFORMAÇÃO========= FRASE.strip tirar os espaços no inicio e no fim de uma frase

DIVISÃO=========== FRASE.split esse comando fatia uma frase COM BASE NOS ESPAÇOS, TRASFORMADO EM UMA LISTA 

JUNÇÃO ============= '--'.JOIN(FRASE)

'''